"""empty message

Revision ID: 89a0e52f10b2
Revises: 84eefc748aa3
Create Date: 2021-03-29 13:26:45.095134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a0e52f10b2'
down_revision = '84eefc748aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'playlist', 'user', ['user_id'], ['id'])
    op.add_column('recommend', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recommend', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recommend', type_='foreignkey')
    op.drop_column('recommend', 'user_id')
    op.drop_constraint(None, 'playlist', type_='foreignkey')
    # ### end Alembic commands ###
